### ISSUE TITLE
Wrong fixed IP address on new Flexible network interface

### ISSUE THREAD

**Issue by lionelg3** [remijouannet/terraform-provider-osc#2]
Using the release "v0.7-hyper-alpha-yolo-experimental" and the osc-fni-1.1.0-8.x86_64.rpm package, I am having issue when setting a fix IP address on a second network card (Flexible network interfaces).

After deployment, the IP address set to the new network card is not the one I have defined. 

```
resource "osc_network_interface" "TEST-IF-VM-TEST1-ADMIN" {
  subnet_id = "${osc_subnet.TEST-SUBNET-ADMIN.id}"
  private_ips = ["10.254.3.80"]
  source_dest_check = "false"
  attachment {
    device_index = 1
    instance     = "${osc_instance.VM-TEST1.id}"
  }
  ...
}
```

The Cockpit interface always 2 IP address, one is automaticaly assigned and the one I choose. But one I choose is not set to the interface.

Thank for your help.

**Comment by remijouannet** [comment]
Hello Lionel,

you can try the release v0.7.1, don't use private_ips but private_ip and specify source_dest_check because outscale API don't handle it for fni

`resource "osc_network_interface" "TEST-IF-VM-TEST1-ADMIN" {
  subnet_id = "${osc_subnet.TEST-SUBNET-ADMIN.id}"
  private_ip = "10.254.3.80"

  attachment {
    device_index = 1
    instance     = "${osc_instance.VM-TEST1.id}"
  }
  ...
}`

**Comment by lionelg3** [comment]
Just try the 0.7.1 version. 

It seems to work fine. I continue testing and give you info very soon.

**Comment by lionelg3** [comment]
Your fix resolv the problem. 
I can now use the Flexible network interface with Terraform.

Thank you for your help fixing this problem.
